#!/usr/bin/env sh

YABAI="$(command -v yabai)"

if [ -z "$YABAI" ]; then
    echo "yabai is not available in PATH" >&2
    exit 1
fi

"$YABAI" -m config layout bsp
"$YABAI" -m config split_ratio 0.50

"$YABAI" -m config top_padding 0
"$YABAI" -m config bottom_padding 0
"$YABAI" -m config left_padding 0
"$YABAI" -m config right_padding 0
"$YABAI" -m config window_gap 4

"$YABAI" -m config mouse_follows_focus off
"$YABAI" -m config focus_follows_mouse off
"$YABAI" -m config mouse_modifier alt
"$YABAI" -m config mouse_action1 move
"$YABAI" -m config mouse_action2 resize

"$YABAI" -m rule --add app="^System Settings$" manage=off
"$YABAI" -m rule --add app="^Calculator$" manage=off
